name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.24.2"
          channel: stable

      - name: Check Flutter doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4.4.0
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

